# Generated by Django 3.2.18 on 2023-05-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='featured_image',
        ),
    ]
